# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\" \n\rKeylogRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x0eKeylogResponse\x12\x10\n\x08response\x18\x01 \x01(\x08\"_\n\x11ScreenshotRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x11\n\tclient_id\x18\x04 \x01(\t\"6\n\x12ScreenshotResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2y\n\rKeylogService\x12-\n\nSendKeylog\x12\x0e.KeylogRequest\x1a\x0f.KeylogResponse\x12\x39\n\x0eSendScreenshot\x12\x12.ScreenshotRequest\x1a\x13.ScreenshotResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYLOGREQUEST']._serialized_start=16
  _globals['_KEYLOGREQUEST']._serialized_end=48
  _globals['_KEYLOGRESPONSE']._serialized_start=50
  _globals['_KEYLOGRESPONSE']._serialized_end=84
  _globals['_SCREENSHOTREQUEST']._serialized_start=86
  _globals['_SCREENSHOTREQUEST']._serialized_end=181
  _globals['_SCREENSHOTRESPONSE']._serialized_start=183
  _globals['_SCREENSHOTRESPONSE']._serialized_end=237
  _globals['_KEYLOGSERVICE']._serialized_start=239
  _globals['_KEYLOGSERVICE']._serialized_end=360
# @@protoc_insertion_point(module_scope)
